export interface IProcessos {
    	
regional_cnj: boolean;
numeroAlternativo: string;
vara: string;
classeNatureza: string;
movs: [];
distribuicaoTipo: string;
situacao: string;
juiz: string;
area: string;
assuntoExtra: string;
liminar: string;
audiencias:	[];
vara_original: string
extinto: number;
gratuita: string;
valor: number;
anexos:	[];
alteradoEm: string;
fonte_sistema: number;
foro: string;
situacao_situacaoID: string;
sentencaData: string;
instancia: number;
processosRelacionados: [];
numero: string;
customs: [];
flag: number;
comarca_cnj: number;
comarca: string;
tribunalID: number;
classeNatureza_dg: number;
foro_cnj: number;
tribunal: string;
processoID: number;
distribuicaoData: string
segredo_justica: boolean
arquivado: boolean
classes: [];
acessos: [];
uf: string
criadoEm: string;
partes:	[];
}